= 前提知識

== 3 （ n ）層（ Tier ）アーキテクチャと 3 （ n ）レイヤー（ Layer ）アーキテクチャ

.層（ Tier ）とレイヤー（ Layer ）
[quote, IBM, 'https://www.ibm.com/jp-ja/topics/three-tier-architecture[3層アーキテクチャーとは]']
____
層とレイヤーは同じではありません。 「レイヤー」とは、ソフトウェアの機能部を指しますが、
「層」とは、他の部分から分離してインフラストラクチャーで実行されるソフトウェアの機能部を指します。 
例えば、電話の連絡先アプリは、3レイヤー・アプリケーションですが、3つのレイヤーがすべてその電話上で機能するため、1層 のアプリケーションです。
____


=== 3 （ n ）層（ Tier ）アーキテクチャ

古くから Web アプリケーションなどで使われている一般的な構造

物理的に分けることが可能な「層」

アプリケーション内での論理的な分割である 3 レイヤー（ Layer 、層）アーキテクチャや
ヘキサゴナルアーキテクチャの前提となっているレイヤードアーキテクチャと構造や用語が似ており混同を
避けるために紹介する。


参考）
* https://www.ibm.com/jp-ja/topics/three-tier-architecture[3層アーキテクチャーとは]
* https://docs.aws.amazon.com/whitepapers/latest/serverless-multi-tier-architectures-api-gateway-lambda/welcome.html[AWS Serverless Multi-Tier Architectures with Amazon API Gateway and AWS Lambda]
* https://learn.microsoft.com/ja-jp/windows/win32/cossdk/using-a-three-tier-architecture-model[3 層アーキテクチャ モデルの使用]


プレゼンテーション層、ユーザーサービス層::
  プレゼンテーション層とは、アプリケーションのユーザー・インターフェースかつアプリケーションの通信層であり、エンド・ユーザーはこの層でアプリケーションと対話します。 
  その主な目的は、ユーザーに情報を表示し、情報をユーザーから収集することです。 
  この第1層は、デスクトップ・アプリケーションであるWebブラウザー、またはグラフィカル・ユーザー・インターフェース（GUI）などで実行できます。
  Webプレゼンテーション層は通常、HTML、CSS 、JavaScriptを使用して開発されます。 デスクトップ・アプリケーションは、プラットフォームに応じてさまざまな言語で記述することができます。
アプリケーション層、論理層、中間層、ビジネスサービス層、ビジネスロジック層::
  アプリケーション層（論理層または中間層とも呼ばれます）は、アプリケーションの中核です。
  この層では、プレゼンテーション層で収集された情報が、特定のビジネス・ルールのセットであるビジネス・ロジックを使用して処理されます
  （データ層の他の情報に対して処理される場合もあります）。 アプリケーション層は、データ層内でデータの追加、削除、または変更を行うこともできます。 
データ層、データサービス層::
  データ層（データベース層、データ・アクセス層、またはバックエンドと呼ばれることもあります）は、アプリケーションによって処理された情報が保管され、管理される場所です。
  これは、PostgreSQL、MySQL、MariaDB、Oracle、Db2、Informix、Microsoft SQL Serverなどのリレーショナル・データベース管理システムである場合、またはCassandra、CouchDB、MongoDBなどの
  NoSQLデータベース・サーバー内にある場合があります。          

3層アプリケーションでは、すべての通信がアプリケーション層を経由します。 プレゼンテーション層とデータ層は、相互に直接通信できません。

=== Web アプリケーションの例

単純にクライアント層とサーバ層の 2 層とする考え方もあるが、ここでは n 層に分けた場合を考える。

1 層目::
  クライアントマシン。役割としてはプレゼンテーション層。マシン内は Web ブラウザなど。
2 層目::
  Web サーバマシン。役割としてはプレゼンテーション層。マシン内は Apache HTTP Server や Nginx など。
3 層目::
  アプリケーションサーバマシン。役割としてはアプリケーション層。マシン内は Apache Tomcat など。
4 層目::
  DB サーバマシン。役割としてはデータ層。マシン内は PostgreSQL など。

補足）

* クライアントマシンはサービスの外と見てこれを除いたサーバ側だけで 3 層と呼ばれるのが多そう。
* Web サーバマシンとアプリケーションサーバマシンを共通のものとして中間層とした場合もある。参考 : https://www.ibm.com/docs/ja/db2-for-zos/13?topic=environment-architectural-characteristics-web-based-applications[Web ベース・アプリケーションのアーキテクチャーの特性]


=== 3 （ n ）レイヤー（ Layer ）アーキテクチャ

物理層のうち、アプリケーション層の中の話




== レイヤードアーキテクチャ

ドメインの概念の登場




== ドメイン駆動設計



入力側や出力側という表現だけではイメージしやすいかもしれないが、
入力へのレスポンスや出力されたデータの参照などが分かりにくくなるため、
公式の例のようにユーザサイドやデータサイド、オニオンアーキテクチャなどの U/I やインフラストラクチャなどの表現の方が良さそう
クリーンアーキテクチャだとコントローラーが入力とプレゼンテーターが出力となってデバイスを通してインフラストラクチャにアクセス
しそうに見える

ポート アプリケーション境界の内外のやり取りに利用
ユースケース アプリケーション境界上の内側に存在
ユースケースをポート（アプリケーション境界そのもの）の一部とするか、ポートとは区切られた内側の層とするか？
＝＞ クリーンアーキテクチャだと、境界線そのものがユースケース層であり、入力／出力ポートとインターアクターが存在する。
よって、ポートの一部と見るのが自然っぽい。ただし、外側とやり取りするのは入出力ポートの役割



アプリケーション



アプリケーションの具体化

オニオンアーキテクチャ

クリーンアーキテクチャ



ドメイン駆動設計（ DDD ）との関係

ドメインとは






依存方向
依存関係の逆転
自分と同じ層とさらに内側しか知らない。
知らないものが変更されても何も影響は受けずに済む。
セカンダリ側だと処理の流れと依存関係が逆になるが、そこはインターフェースを介して実装に処理を
渡すことで解消できる



実装順

アダプタやポートはテスト用から

