= ヘキサゴナルアーキテクチャ

== レイヤー

.ヘキサゴナルアーキテクチャにおけるレイヤー
[cols="1,1,1"options="noheader,autowidth",stripes=hover]
|===
^a| *アクター*
^|プライマリアクター
^|セカンダリアクター

^a| *アダプタ*
^a|プライマリアダプタ（ #ユーザーインターフェース層# ）
^a|セカンダリアダプタ（ #インフラストラクチャ層# ）

^a| *アプリケーション* （ #アプリケーション層# 、#ドメイン層# ）
2+^a|プライマリポート、セカンダリポート、その他アプリケーションロジック、ドメインモデル、ビジネスロジック
|===

なお、オニオンアーキテクチャやクリーンアーキテクチャではアプリケーション部分がさらにレイヤー分け／詳細化されている。





入力側や出力側という表現だけではイメージしやすいかもしれないが、
入力へのレスポンスや出力されたデータの参照などが分かりにくくなるため、
公式の例のようにユーザサイドやデータサイド、オニオンアーキテクチャなどの U/I やインフラストラクチャなどの表現の方が良さそう
クリーンアーキテクチャだとコントローラーが入力とプレゼンテーターが出力となってデバイスを通してインフラストラクチャにアクセス
しそうに見える

アダプタについてはプライマリ側をエントリーポイント、セカンダリ側をアダプタと呼んでる例もあり

参考 : https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/hexagonal-architectures/best-practices.html[AWS Prescriptive Guidance, Building hexagonal architectures on AWS, Best practices]

ポート アプリケーション境界の内外のやり取りに利用
ユースケース アプリケーション境界上の内側に存在
ユースケースをポート（アプリケーション境界そのもの）の一部とするか、ポートとは区切られた内側の層とするか？
＝＞ クリーンアーキテクチャだと、境界線そのものがユースケース層であり、入力／出力ポートとインターアクターが存在する。
よって、ポートの一部と見るのが自然っぽい。ただし、外側とやり取りするのは入出力ポートの役割

