= 実装サンプル）単純計算アプリケーション

https://github.com/totheralistair/SmallerWebHexagon[Smaller Web Hexagon] に
記載されているサンプルを一部改造しつつ Java で実装する。

入力値に対して対応するレートを使った計算を行い、計算結果と使用したレートを返却するアプリケーション

== システム概要図


== ユースケース

参考にした作成方法 : https://qiita.com/putan/items/580cbc6f136859f82edb[Quiita, ユースケースをモデリングする]

https://it-koala.com/usecasediagrams-1832

include::usecases.adoc[]



概要ユースケース図


詳細ユースケース図


== 設計

コアとなるレイヤーから設計していく。

=== 全体像

++++
<div class="mermaid">
classDiagram
direction LR
include::uml/class_domain01.uml[]
include::uml/class_appservice.uml[]
include::uml/class_primary_adapter.uml[]
include::uml/class_secondary_adapter.uml[]

</div>
++++



=== ドメインレイヤー

入力値に対して対応するレートを使った計算を行い、計算結果と使用レートを返却する。
計算に失敗した場合は失敗理由を返却する。


クラス図


++++
<div class="mermaid">
classDiagram
direction LR
include::uml/class_domain01.uml[]
</div>
++++

入力値などもモデリングが必要で値オブジェクトとする場合は以下のような集約やコンポジションとなる。
（より複雑なパターンとして他のサンプルで例を示す予定）

++++
<div class="mermaid">
include::uml/class02.uml[]
</div>
++++




シーケンス図

++++
<div class="mermaid">
include::uml/sequence.uml[]
</div>
++++


==== オブジェクト

制約がゆるく値オブジェクトとしてモデリングは行わず、データ型（言語に用意されているプリミティブ型や列挙型など）で十分な属性の
例として、ここではレート値については値オブジェクトにしない。

===== エンティティ


.エンティティ一覧
[cols="1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|計算レート
a|計算に利用するレート。計算の入力値で一意に決まる。

|===


.計算レート詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|id
|属性
|private
|id : 計算入力値
a|レートを決定する ID 。ここでは計算の入力値を利用する。

|rate
|属性
|private
|rate : double
a|計算時にレートとして使われる値

|生成()
|操作
|public
|生成(id : 計算入力値, rate : double) : 計算レート
a|本エンティティのインスタンスを生成する
|===


.サンプルソース（ Java ）：レート
[source,java]
----
include::src/sampleapp/src/main/java/sample/application/domain/object/entity/RateEntity.java[]
----


===== 値オブジェクト

できれば抽象クラスとして値オブジェクトクラスを作って継承させたいが、ややこしいため今回は保留

制約チェックが発生させる例外は値オブジェクトとしては定義しないが、 UML のクラス図には制約チェックと関連のあるクラスとして記載。
ドメインイベントとしては表現できないか？
アプリケーションとしての例外ではなく、ドメインとして考慮された仕様上のエラーとしたい
問題が起きて処理が中断されたのではなく、仕様通りにチェックが終わった結果不当だった、という話なので、
例外ではなく復帰値で表現すべき？
＝＞ java の仕様で考えるなら非チェック例外（呼び出し側の使い方が悪い扱い）でも良いかも
＝＞コンストラクタとしては非チェック例外で生成が中断された、で良いが制約チェックとしては復帰値の方が自然？
＝＞正常時に欲しい結果が存在しないため、復帰値は void で失敗時情報は例外で良さそう

ドメイン層は生成時に生成物か例外を返却して、アプリケーション層などの実装で処理を分ける。

☆ドメインとしては制約違反は致命的な異常として検査例外として、アプリケーション層でそれをどう扱うか次第で
非検査例外で包む

例外のドメインモデルと自然なのは？
制約違反？
エンティティ？値オブジェクト？その他（無秩序になるのは避けたい）？
＝＞値オブジェクトなどにはし辛いが、制約違反自体のモデルは必要なものなので一旦その他にしておく

複数オブジェクト間の制約チェックはチェッカーサービスを用意
制約がユースケースに依存する場合はインターフェース



.値オブジェクト一覧
[cols="1,1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|計算入力値
a|計算の入力となる値


|計算結果値
a|計算の結果となる値

|===


.計算入力値詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|value
|属性
|private
|value : int
a|入力となる値

|生成()
|操作
|public
|生成(value : int) : 計算入力値
a|本値オブジェクトのインスタンスを生成する

|制約チェック()
|操作
|public
|制約チェック() : void
a|本値オブジェクトの値が正しいかチェックする。正しくない場合は例外を発生する。
|===


.計算結果値詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|result
|属性
|private
|result : double
a|計算結果の値

|rate
|属性
|private
|rate : double
a|計算に使われたレートの値

|生成()
|操作
|public
|生成(result : double, rate : double) : 計算結果値
a|本値オブジェクトのインスタンスを生成する


|制約チェック()
|操作
|public
|制約チェック() : void
a|本値オブジェクトの値が正しいかチェックする。正しくない場合は例外を発生する。
|===



==== サービス

プライマリポートのインターフェース

計算実行
入力 入力値
出力 計算結果値




==== ライフサイクル

エンティティに対するライフサイクルパターン


集約

集約ルート
レート



リポジトリ
レート


== アプリケーションレイヤー



ポート 2 つだけの単純な構造


コンテキストは 1 つとする。








サービスとプライマリポートの扱いは調査中

サービスにポートとなるインターフェースとその実装の両方を含める？

=== サービス

ユースケースに応じてプライマリポートとセカンダリポートを繋げる役割を持つ。

プライマリポートの実装
セカンダリポートの呼び出し



=== ポート

ポートは入出力を定義
入出力はリクエストとレスポンス
レスポンスは結果そのものだけではなく、正常異常のステータスも必須

==== プライマリポート

ユーザサイドポート

入力値を受け取って計算結果とレートを返す。

DDD としての役割 サービス？
Java としての実装 インターフェース




==== セカンダリポート

データサイドポート

入力値を元にレートを取得

DDD におけるリポジトリ

インターフェースとして実装

DDD としての役割 リポジトリ
Java としての実装 インターフェース







== アダプタ

プライマリアダプタ
CUI アダプタ
HTTP アダプタ
テストアダプタ

セカンダリアダプタ
モック（インメモリ）アダプタ
ファイルシステムアダプタ


ポートの実装として実装


== アクター



プライマリアクター
ユーザ（人）
HTTP リクエスト
テストスクリプト


セカンダリアクター
モック（インメモリ）
ファイルシステム
DBMS





アダプタのファクトリ

ドメインのファクトリとは別の話
サービスやリポジトリをドメインのインターフェース／アダプタの実装で分けると
実装の方を色々切り替える可能性があるので、実装を選択したインスタンス作成をしやすくするのに使える？
レートリポジトリファクトリー
レートリポジトリの実装を選択
プライマリアクターはファクトリーでリポジトリ種別を指定してリポジトリインスタンスを取得してプライマリアダプタに入力する？
ファクトリーの実装で対応していないリポジトリはアクターが直接参照して利用




== ディレクトリ構成

レイヤーで記載した分類に合わせる。












