= 実装サンプル）単純計算アプリケーション

https://github.com/totheralistair/SmallerWebHexagon[Smaller Web Hexagon] に
記載されているサンプルを Java で実装する。

入力値に対して対応するレートを使った計算を行い、計算結果と使用したレートを返却するアプリケーション


== ユースケース

参考にした作成方法 : https://qiita.com/putan/items/580cbc6f136859f82edb[Quiita, ユースケースをモデリングする]

https://it-koala.com/usecasediagrams-1832

include::usecases.adoc[]



概要ユースケース図
詳細ユースケース図




== アプリケーション（ドメイン）



ポート 2 つだけの単純な構造

値オブジェクト
エンティティ

入力値
レート
計算結果？

レート一覧
DDD における集約として実装



クラス図

[plantuml, target=class01, format=svg]
....
include::_uml/class01.puml[]
....


=== サービス

プライマリポートとセカンダリポートを繋げる役割を持つ。




=== ポート

ポートは入出力を定義
入出力はリクエストとレスポンス
レスポンスは結果そのものだけではなく、正常異常のステータスも必須

==== プライマリポート

ユーザサイドポート

入力値を受け取って計算結果とレートを返す。

DDD としての役割 サービス
Java としての実装 インターフェース




==== セカンダリポート

データサイドポート

入力値を元にレートを取得

DDD におけるリポジトリ

インターフェースとして実装

DDD としての役割 リポジトリ
Java としての実装 インターフェース


== アダプタ

プライマリアダプタ
CUI アダプタ
HTTP アダプタ
テストアダプタ

セカンダリアダプタ
モック（インメモリ）アダプタ
ファイルシステムアダプタ


ポートの実装として実装


== アクター



プライマリアクター
ユーザ（人）
HTTP リクエスト
テストスクリプト


セカンダリアクター
モック（インメモリ）
ファイルシステム
DBMS


















