= 実装サンプル）単純計算アプリケーション

https://github.com/totheralistair/SmallerWebHexagon[Smaller Web Hexagon] に
記載されているサンプルを一部改造しつつ Java で実装する。

入力値に対して対応するレートを使った計算を行い、計算結果と使用したレートを返却するアプリケーション

== システム概要図


== ユースケース

参考にした作成方法 : https://qiita.com/putan/items/580cbc6f136859f82edb[Quiita, ユースケースをモデリングする]

https://it-koala.com/usecasediagrams-1832

include::usecases.adoc[]



概要ユースケース図


詳細ユースケース図


== 設計

コアとなるレイヤーから設計していく。

=== 全体像

++++
<div class="mermaid">
classDiagram
direction LR
include::uml/domain/class01.uml[]
include::uml/application/class.uml[]
include::uml/class_primary_adapter.uml[]
include::uml/class_secondary_adapter.uml[]

</div>
++++

シーケンス図

++++
<div class="mermaid">
sequenceDiagram
include::uml/application/sequence.uml[]
</div>
++++

シーケンス図は処理の流れや相互作用の意味合いが強いのでドメイン層の中ではなく
アプリケーション層でドメイン層をどう使うかの話になりそう

ユースケースによって内容が変わるが、アクターやアダプタでは変わらないはず


=== ドメインレイヤー

入力値に対して対応するレートを使った計算を行い、計算結果と使用レートを返却する。
計算に失敗した場合は失敗理由を返却する。


クラス図

例外パターン

++++
<div class="mermaid">
classDiagram
direction LR
include::uml/domain/class01.uml[]
</div>
++++

復帰値パターン

++++
<div class="mermaid">
classDiagram
direction LR
include::uml/domain/class02.uml[]
</div>
++++




==== オブジェクト



===== エンティティ


アプリケーションの発注単位となる「計算」もエンティティにするか？
レート集約／リポジトリとの関係は？計算リポジトリまで登場するとやりすぎ？
その場合は計算ログまでやるほうが自然


.エンティティ一覧
[cols="1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|計算レート
a|計算に利用するレート
|===


.計算レート詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|id
|属性
|private
|id : id
a|レートを決定する ID 。計算の入力値で一意に決まるが、レートの ID と計算入力値は分けて考えれるようにしたい
（実装によって id の許容値を変える、入力値以外を id に変えるなど）ため、ここでは計算入力値と関連付けはしない。

|rate
|属性
|private
|rate : double
a|計算時にレートとして使われる値

|生成()
|操作
|public
|生成(id : int, rate : double) : 計算レート
a|本エンティティのインスタンスを生成する

|属性値取得（属性ごとに用意）()
|操作
|public
|属性値取得() : 各属性の型
a|各属性の値を取得する。属性ごとに用意

|制約チェック()
|操作
|public
|制約チェック() : void
a|本値オブジェクトの値が正しいかチェックする。正しくない場合は例外を発生する。
|===


.サンプルソース（ Java ）：レート
[source,java]
----
include::src/sampleapp/src/main/java/sample/application/domain/object/entity/RateEntity.java[]
----


===== 値オブジェクト

各フィールドの getter は記載省略。不変値のため setter は使わない。


できれば抽象クラスとして値オブジェクトクラスを作って継承させたいが、ややこしいため今回は保留

制約チェックが発生させる例外は値オブジェクトとしては定義しないが、 UML のクラス図には制約チェックと関連のあるクラスとして記載。
ドメインイベントとしては表現できないか？
アプリケーションとしての例外ではなく、ドメインとして考慮された仕様上のエラーとしたい
問題が起きて処理が中断されたのではなく、仕様通りにチェックが終わった結果不当だった、という話なので、
例外ではなく復帰値で表現すべき？

参考 : https://zenn.dev/koduki/articles/e9373cb78fcfef

＝＞ java の仕様で考えるなら非チェック例外（呼び出し側の使い方が悪い扱い）でも良いかも
＝＞コンストラクタとしては非チェック例外で生成が中断された、で良いが制約チェックとしては復帰値の方が自然？
＝＞正常時に欲しい結果が存在しないため、復帰値は void で失敗時情報は例外で良さそう


ドメイン層は生成時に生成物か例外を返却して、アプリケーション層などの実装で処理を分ける。

☆ドメインとしては制約違反は実現したい概念が成り立たない致命的な異常として検査例外として、アプリケーション層でそれをどう扱うか次第で
非検査例外（インターフェース側で throws 定義していなくても実装側で throw 可能）で包む

参考 : https://qiita.com/ts7i/items/d7f6c1cd5a14e55943d4

非検査例外だと失敗を見逃しやすいというリスクを優先するのであれば、ポートとなるインターフェースに対しては
～結果や～失敗理由といった抽象クラスを復帰値用に用意し、ポートの実装側でそれらの実装も行うのが良いか？
その方がポート利用者に正常時だけではなく処理失敗時の扱いも指定できる。
ここでは非正規例外／復帰値両パターンを用意してみる。


例外のドメインモデルと自然なのは？
制約違反？
エンティティ？値オブジェクト？その他（無秩序になるのは避けたい）？
＝＞値オブジェクトなどにはし辛いが、制約違反自体のモデルは必要なものなので一旦その他にしておく

複数オブジェクト間の制約チェックはチェッカーサービスを用意
制約がユースケースに依存する場合はインターフェース

一覧には載せないが、属性が 1 つだけの単純なものが増えた場合に備えて、
汎用化した「シンプル値オブジェクト」クラスを用意してそれを継承させる。
（属性の型は Java のジェネリクス機能で可変にしておく）


.値オブジェクト一覧
[cols="1,1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|計算入力値
a|計算の入力となる値

|計算結果値
a|計算の結果となる値
|===


.計算入力値詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|value
|属性
|private
|value : Integer
a|入力となる値

|生成()
|操作
|public
|生成(value : Integer) : 計算入力値
a|本値オブジェクトのインスタンスを生成する

|属性値取得（属性ごとに用意）()
|操作
|public
|属性値取得() : 各属性の型
a|各属性の値を取得する。属性ごとに用意

|制約チェック()
|操作
|public
|制約チェック() : void
a|本値オブジェクトの値が正しいかチェックする。正しくない場合は例外を発生する。
|===


.計算結果値詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|result
|属性
|private
|result : double
a|計算結果の値

|rate
|属性
|private
|rate : double
a|計算に使われたレートの値

|生成()
|操作
|public
|生成(result : double, rate : double) : 計算結果値
a|本値オブジェクトのインスタンスを生成する

|属性値取得（属性ごとに用意）()
|操作
|public
|属性値取得() : 各属性の型
a|各属性の値を取得する。属性ごとに用意

|制約チェック()
|操作
|public
|制約チェック() : void
a|本値オブジェクトの値が正しいかチェックする。正しくない場合は例外を発生する。
|===


===== ドメイン例外

すべてのクラスで発生するはず（オブジェクトも生成操作は必須）なので UML クラス図上は関連の線は省略
生成時の制約チェックやサービスでの複数オブジェクト操作など、操作の種別で例外を分けるのであれば
それらに対して関連の線を書くのはあり（例外の名前だけ見ればどのクラスで発生するか想像できる方が理想かも？）

.例外一覧
[cols="1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|ドメイン例外
a|ドメイン上の操作で発生する例外全般。その他のドメイン例外のベースとなるもの。例外内容に応じて他の例外を追加
|===



==== サービス

ドメインとしては役割だけ用意して実装方法までは意識しないはずなので、インターフェースを用意。
少なくともプライマリポートのインターフェースとなる。その他の用途はここでは出てこない。

計算実行
入力 入力値
出力 計算結果値


.サービス一覧
[cols="1,1,1"options="header,autowidth",stripes=hover]
|===
| 名前 |説明

|計算サービスインターフェース
a|計算を実行する
|===


.計算サービスインターフェース詳細
[cols="1,1,1,1,2"options="header,autowidth",stripes=hover]
|===
| 名前 | 種別 | 可視性 | 詳細 | 説明

|計算()
|操作
|public
|計算(input : 計算入力値) : 計算結果値
a|入力値を元にレート値を使った計算を実行し、計算結果値を返却する。
|===


==== ライフサイクル

エンティティに対するライフサイクルパターン


集約

集約ルート
レート



リポジトリ
レート


== アプリケーションレイヤー



ポート 2 つだけの単純な構造


コンテキストは 1 つとする。








サービスとプライマリポートの扱いは調査中

サービスにポートとなるインターフェースとその実装の両方を含める？

=== サービス

ユースケースに応じてプライマリポートとセカンダリポートを繋げる役割を持つ。

プライマリポートの実装
セカンダリポートの呼び出し



=== ポート

ポートは入出力を定義
入出力はリクエストとレスポンス
レスポンスは結果そのものだけではなく、正常異常のステータスも必須

==== プライマリポート

ユーザサイドポート

入力値を受け取って計算結果とレートを返す。

DDD としての役割 サービス？
Java としての実装 インターフェース




==== セカンダリポート

データサイドポート

入力値を元にレートを取得

DDD におけるリポジトリ

インターフェースとして実装

DDD としての役割 リポジトリ
Java としての実装 インターフェース







== アダプタ

プライマリアダプタ
CUI アダプタ
HTTP アダプタ
テストアダプタ

セカンダリアダプタ
モック（インメモリ）アダプタ
ファイルシステムアダプタ


ポートの実装として実装


== アクター



プライマリアクター
ユーザ（人）
HTTP リクエスト
テストスクリプト


セカンダリアクター
モック（インメモリ）
ファイルシステム
DBMS





アダプタのファクトリ

ドメインのファクトリとは別の話
サービスやリポジトリをドメインのインターフェース／アダプタの実装で分けると
実装の方を色々切り替える可能性があるので、実装を選択したインスタンス作成をしやすくするのに使える？
レートリポジトリファクトリー
レートリポジトリの実装を選択
プライマリアクターはファクトリーでリポジトリ種別を指定してリポジトリインスタンスを取得してプライマリアダプタに入力する？
ファクトリーの実装で対応していないリポジトリはアクターが直接参照して利用




== ディレクトリ構成

レイヤーで記載した分類に合わせる。












